development: &DEVELOPMENT
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: data-savant_development
  pool: 5
  username: root
  password:

hotfix:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: data-savant_hotfix
  pool: 5
  username: root
  password:

test: &TEST
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: data-savant_test
  pool: 5
  username: root
  password:

production: &PRODUCTION
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: data-savant_production
  pool: 5
  username: root
  password: